# Function to find and check dependencies
function(find_and_check_dependency TYPE NAME)
        if(TYPE STREQUAL "PACKAGE")
                find_package(${NAME} REQUIRED)
                if(NOT ${NAME}_FOUND)
                        message(FATAL_ERROR "${NAME} not found! Try using './scripts/setup.sh' to install the required dependencies.")
                endif()
        elseif(TYPE STREQUAL "LIBRARY")
                find_library(FOUND_${NAME} ${NAME})
                if(NOT FOUND_${NAME})
                        message(FATAL_ERROR "${NAME} library not found! Try using './scripts/setup.sh' to install the required dependencies.")
                endif()
        else()
                message(FATAL_ERROR "Invalid dependency type: ${TYPE} [${NAME}]. Use PACKAGE or LIBRARY.")
        endif()
endfunction()